#
# Lua library target
#
set(VENDOR_LUA_DIR "${MTASA_VENDOR_DIR}/lua/src")

add_library(vendor-lua STATIC
    "${VENDOR_LUA_DIR}/lapi.c"
    "${VENDOR_LUA_DIR}/lapi.h"
    "${VENDOR_LUA_DIR}/lauxlib.c"
    "${VENDOR_LUA_DIR}/lauxlib.h"
    "${VENDOR_LUA_DIR}/lbaselib.c"
    "${VENDOR_LUA_DIR}/lcode.c"
    "${VENDOR_LUA_DIR}/lcode.h"
    "${VENDOR_LUA_DIR}/ldblib.c"
    "${VENDOR_LUA_DIR}/ldebug.c"
    "${VENDOR_LUA_DIR}/ldebug.h"
    "${VENDOR_LUA_DIR}/ldo.c"
    "${VENDOR_LUA_DIR}/ldo.h"
    "${VENDOR_LUA_DIR}/ldump.c"
    "${VENDOR_LUA_DIR}/lfunc.c"
    "${VENDOR_LUA_DIR}/lfunc.h"
    "${VENDOR_LUA_DIR}/lgc.c"
    "${VENDOR_LUA_DIR}/lgc.h"
    "${VENDOR_LUA_DIR}/linit.c"
    "${VENDOR_LUA_DIR}/liolib.c"
    "${VENDOR_LUA_DIR}/llex.c"
    "${VENDOR_LUA_DIR}/llex.h"
    "${VENDOR_LUA_DIR}/llimits.h"
    "${VENDOR_LUA_DIR}/lmathlib.c"
    "${VENDOR_LUA_DIR}/lmem.c"
    "${VENDOR_LUA_DIR}/lmem.h"
    "${VENDOR_LUA_DIR}/loadlib.c"
    "${VENDOR_LUA_DIR}/lobject.c"
    "${VENDOR_LUA_DIR}/lobject.h"
    "${VENDOR_LUA_DIR}/lopcodes.c"
    "${VENDOR_LUA_DIR}/lopcodes.h"
    "${VENDOR_LUA_DIR}/loslib.c"
    "${VENDOR_LUA_DIR}/lparser.c"
    "${VENDOR_LUA_DIR}/lparser.h"
    "${VENDOR_LUA_DIR}/lstate.c"
    "${VENDOR_LUA_DIR}/lstate.h"
    "${VENDOR_LUA_DIR}/lstring.c"
    "${VENDOR_LUA_DIR}/lstring.h"
    "${VENDOR_LUA_DIR}/lstrlib.c"
    "${VENDOR_LUA_DIR}/ltable.c"
    "${VENDOR_LUA_DIR}/ltable.h"
    "${VENDOR_LUA_DIR}/ltablib.c"
    "${VENDOR_LUA_DIR}/ltm.c"
    "${VENDOR_LUA_DIR}/ltm.h"
    "${VENDOR_LUA_DIR}/lua.h"
    "${VENDOR_LUA_DIR}/luaconf.h"
    "${VENDOR_LUA_DIR}/lualib.h"
    "${VENDOR_LUA_DIR}/lundump.c"
    "${VENDOR_LUA_DIR}/lundump.h"
    "${VENDOR_LUA_DIR}/lutf8lib.c"
    "${VENDOR_LUA_DIR}/lvm.c"
    "${VENDOR_LUA_DIR}/lvm.h"
    "${VENDOR_LUA_DIR}/lzio.c"
    "${VENDOR_LUA_DIR}/lzio.h"
    "${VENDOR_LUA_DIR}/print.c"
    "${VENDOR_LUA_DIR}/unidata.h"
)

target_include_directories(vendor-lua PUBLIC "${VENDOR_LUA_DIR}")
