name: Scheduled Auto-Merge PRs

on:
  schedule:
    # - cron: '1 0 * * 0'  # This cron expression runs the workflow every Friday at midnight (UTC)
    - cron: '40 1 * * 5'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Auto-merge pull request
        run: |
          PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --author 'MTABot' --base 'l10n/master' --state open --json number --jq '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr merge $PR_NUMBER --squash --repo ${{ github.repository }} --admin --subject "New Crowdin updates (PR #$PR_NUMBER)" --body ""
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
