/*****************************************************************************
 *
 *  PROJECT:     Multi Theft Auto
 *  LICENSE:     See LICENSE in the top level directory
 *  PURPOSE:     Unity build file
 *
 *  Multi Theft Auto is available from https://multitheftauto.com/
 *
 *****************************************************************************/

#include "CBulletsyncPacket.cpp"
#include "CCameraSyncPacket.cpp"
#include "CChatClearPacket.cpp"
#include "CChatEchoPacket.cpp"
#include "CCommandPacket.cpp"
#include "CConsoleEchoPacket.cpp"
#include "CCustomDataPacket.cpp"
#include "CCustomWeaponBulletSyncPacket.cpp"
#include "CDebugEchoPacket.cpp"
#include "CDestroySatchelsPacket.cpp"
#include "CDetonateSatchelsPacket.cpp"
#include "CDiscordJoinPacket.cpp"
#include "CElementRPCPacket.cpp"
#include "CEntityAddPacket.cpp"
#include "CEntityRemovePacket.cpp"
#include "CExplosionSyncPacket.cpp"
#include "CFireSyncPacket.cpp"
#include "CKeysyncPacket.cpp"
#include "CLightsyncPacket.cpp"
#include "CLuaEventPacket.cpp"
#include "CLuaPacket.cpp"
#include "CMapInfoPacket.cpp"
#include "CObjectStartSyncPacket.cpp"
#include "CObjectSyncPacket.cpp"
#include "CPacket.cpp"
#include "CPedStartSyncPacket.cpp"
#include "CPedSyncPacket.cpp"
#include "CPedTaskPacket.cpp"
#include "CPedWastedPacket.cpp"
#include "CPickupHideShowPacket.cpp"
#include "CPickupHitConfirmPacket.cpp"
#include "CPlayerACInfoPacket.cpp"
#include "CPlayerChangeNickPacket.cpp"
#include "CPlayerClothesPacket.cpp"
#include "CPlayerConnectCompletePacket.cpp"
#include "CPlayerDiagnosticPacket.cpp"
#include "CPlayerDisconnectedPacket.cpp"
#include "CPlayerJoinCompletePacket.cpp"
#include "CPlayerJoinDataPacket.cpp"
#include "CPlayerJoinPacket.cpp"
#include "CPlayerListPacket.cpp"
#include "CPlayerModInfoPacket.cpp"
#include "CPlayerNetworkStatusPacket.cpp"
#include "CPlayerPuresyncPacket.cpp"
#include "CPlayerQuitPacket.cpp"
#include "CPlayerScreenShotPacket.cpp"
#include "CPlayerSpawnPacket.cpp"
#include "CPlayerStatsPacket.cpp"
#include "CPlayerTimeoutPacket.cpp"
#include "CPlayerTransgressionPacket.cpp"
#include "CPlayerWastedPacket.cpp"
#include "CProjectileSyncPacket.cpp"
#include "CResourceClientScriptsPacket.cpp"
#include "CResourceStartPacket.cpp"
#include "CResourceStopPacket.cpp"
#include "CReturnSyncPacket.cpp"
#include "CServerInfoSyncPacket.cpp"
#include "CServerTextItemPacket.cpp"
#include "CSyncSettingsPacket.cpp"
#include "CUnoccupiedVehiclePushPacket.cpp"
#include "CUnoccupiedVehicleStartSyncPacket.cpp"
#include "CUnoccupiedVehicleSyncPacket.cpp"
#include "CUpdateInfoPacket.cpp"
#include "CVehicleDamageSyncPacket.cpp"
#include "CVehicleInOutPacket.cpp"
#include "CVehiclePuresyncPacket.cpp"
#include "CVehicleResyncPacket.cpp"
#include "CVehicleSpawnPacket.cpp"
#include "CVehicleTrailerPacket.cpp"
#include "CVoiceDataPacket.cpp"
#include "CVoiceEndPacket.cpp"
